### ISSUE TITLE
Works at first, then stops working (mostly when I resize windows with 3-finger drag)

### ISSUE THREAD

**Issue by yay** [ClementGre/ThreeFingerDragOnWindows#57] opened 2024-05-08 10:27 UTC
My system: Razer Blade 15" (2022) RZ09-0421x, Windows 11 Pro, build 22631.3447
I run the app in admin mode and have tap twice and drag for multiselect disabled in Windows settings.

Sorry, that's all I can tell. Wonder if I can debug this somehow to give you more data to work with?

**Comment by ClementGre** [comment] 2024-05-08 10:58
I think that this is a duplicate of #52.
The bug has been fixed in the latest version 2.0.4, released one hour ago.

**Comment by yay** [comment] 2024-05-08 11:23
Thanks, just downloaded that one, will report back in a couple of days.

**Closed** 2024-05-20 05:46 UTC
Labels: duplicate
