### ISSUE TITLE
ThreeFingerDragOnWindows sometimes inactive

### ISSUE THREAD

**Issue by nvansu** [ClementGre/ThreeFingerDragOnWindows#47] opened 2024-04-11 08:44 UTC
ThreeFingerDragOnWindows sometimes inactive

**Comment by nvansu** [comment] 2024-04-11 08:45
after update Verson 2.03

**Comment by wozaibeijizhuxueya** [comment] 2024-04-16 07:16
+1，I also encountered this problem

**Comment by bozwellox** [comment] 2024-04-16 13:18
I'm also having this problem, although I think it started after a Windows update rather than an update to the application.

**Comment by andreyrd** [comment] 2024-05-04 00:09
I believe it happened after 2.03 as well. And I can't even install an older version because I think it auto-updates?

**Comment by ClementGre** [comment] 2024-05-05 08:15
Have you noticed that when the app is getting inactive, single contact mode switches to false, then, only one contact is reported, even if you use multiple fingers?

![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/56594712/043bda1d-1d44-4ebe-afb7-efcc68fdf6cd)

I think this might be a duplicate of #52.

> And I can't even install an older version because I think it auto-updates?
You should be able to install the v2.0.2 form GitHub uninstalling the v2.0.3 first.

**Comment by bozwellox** [comment] 2024-05-07 13:21
Thanks.

**Comment by andreyrd** [comment] 2024-05-07 22:45
> Have you noticed that when the app is getting inactive, single contact mode switches to false, then, only one contact is reported, even if you use multiple fingers?

Yes this is exactly what's happening.

**Comment by ClementGre** [comment] 2024-05-08 06:02
Closed as duplicate of #52.

**Closed by ClementGre** 2024-05-08 06:02 UTC
