### ISSUE TITLE
Provide toolbar icon hiding

### ISSUE THREAD

**Issue by LantoZheng** [ClementGre/ThreeFingerDragOnWindows#74] opened 2024-10-27 07:01 UTC
Since your icons are not very elegant and brief, which affect the appearance of the taskbar, it is recommended to provide a toolbar hiding function.

**Comment by ClementGre** [comment] 2024-10-27 15:11
Duplicate of #37 

If you think putting the icon in the tray is still annoying, feel free to comment on #37.

**Closed by ClementGre** 2024-10-27 15:11 UTC
Labels: duplicate
